# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"n\n\x0ePaymentRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x11\n\ttenant_id\x18\x05 \x01(\t\"_\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\".\n\x14PaymentStatusRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"u\n\x15PaymentStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"Z\n\rRefundRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\"Y\n\x0eRefundResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\trefund_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t2\xea\x01\n\x0ePaymentService\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12Q\n\x10GetPaymentStatus\x12\x1d.payment.PaymentStatusRequest\x1a\x1e.payment.PaymentStatusResponse\x12@\n\rRefundPayment\x12\x16.payment.RefundRequest\x1a\x17.payment.RefundResponseB\x0fZ\rpayment/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rpayment/proto'
  _globals['_PAYMENTREQUEST']._serialized_start=26
  _globals['_PAYMENTREQUEST']._serialized_end=136
  _globals['_PAYMENTRESPONSE']._serialized_start=138
  _globals['_PAYMENTRESPONSE']._serialized_end=233
  _globals['_PAYMENTSTATUSREQUEST']._serialized_start=235
  _globals['_PAYMENTSTATUSREQUEST']._serialized_end=281
  _globals['_PAYMENTSTATUSRESPONSE']._serialized_start=283
  _globals['_PAYMENTSTATUSRESPONSE']._serialized_end=400
  _globals['_REFUNDREQUEST']._serialized_start=402
  _globals['_REFUNDREQUEST']._serialized_end=492
  _globals['_REFUNDRESPONSE']._serialized_start=494
  _globals['_REFUNDRESPONSE']._serialized_end=583
  _globals['_PAYMENTSERVICE']._serialized_start=586
  _globals['_PAYMENTSERVICE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
